// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-6gaWP47tr2NFCdnW5diUBnwPVHazbk',
    appId: '1:694759711512:web:5684114f41bce4885cf46d',
    messagingSenderId: '694759711512',
    projectId: 'petrol-7cf7a',
    authDomain: 'petrol-7cf7a.firebaseapp.com',
    storageBucket: 'petrol-7cf7a.appspot.com',
    measurementId: 'G-WSMPGDP9H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC3KChXIBlK__DE_qDNlvB1L5pNMkNyV4',
    appId: '1:694759711512:android:170e913d95933bd25cf46d',
    messagingSenderId: '694759711512',
    projectId: 'petrol-7cf7a',
    storageBucket: 'petrol-7cf7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2DBLXK3j-OeWXOR_Qj6Yx2Z2Aq_A_ls',
    appId: '1:694759711512:ios:ddca383d953d5b595cf46d',
    messagingSenderId: '694759711512',
    projectId: 'petrol-7cf7a',
    storageBucket: 'petrol-7cf7a.appspot.com',
    iosBundleId: 'com.example.petrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2DBLXK3j-OeWXOR_Qj6Yx2Z2Aq_A_ls',
    appId: '1:694759711512:ios:adbbc29501b8e0875cf46d',
    messagingSenderId: '694759711512',
    projectId: 'petrol-7cf7a',
    storageBucket: 'petrol-7cf7a.appspot.com',
    iosBundleId: 'com.example.petrol.RunnerTests',
  );
}
